# -*- coding: utf-8 -*-
"""47_Inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kFfrblAPSpjGImzOpVwVsLMzFqy4LVwt
"""

import argparse
import cv2
import numpy as np
import os
from tensorflow.keras.models import load_model


parser = argparse.ArgumentParser(description='House Prices Regression Inference')

parser.add_argument('--data',  help='data path', default='HouseImage1')
parser.add_argument('--model', help='model path', default='cnn-HousePricesImageRegression.h5')

args = parser.parse_args()

model = load_model(args.model)

images = []
outputImage = np.zeros((64, 64, 3), dtype="uint8")

for img in os.listdir(args.data):
  image = cv2.imread(os.path.join(args.data, img))
  image = cv2.resize(image, (32, 32))
  images.append(image)


outputImage[0:32, 0:32] = images[0]
outputImage[0:32, 32:64] = images[1]
outputImage[32:64, 32:64] = images[2]
outputImage[32:64, 0:32] = images[3]

outputImage = np.array(outputImage)
outputImage = outputImage / 255.0

outputImage = outputImage.reshape(1, 64, 64, 3)
pred = model.predict([outputImage])
print('House price estimated : ', pred)

