# -*- coding: utf-8 -*-
"""carDetector_Inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGJYccCLl4adQlgb8aTlQhDIPnKCVzi_
"""

import argparse
import cv2
import numpy as np
from tensorflow.keras.models import load_model

from google.colab import drive
drive.mount("/content/drive/")

model = load_model('/content/drive/MyDrive/models/44-carTypeDetector-cnn.h5')

parser = argparse.ArgumentParser(description='carDetector inference')
parser.add_argument('--data', type=str, help='data path, Ex: /data/img.jpg', default='/content/drive/MyDrive/datasets/Inference/cars/image.jpg')

args = parser.parse_args()

image = cv2.imread(args.data)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (width, height))
image = image / 255
image = image.reshape(1, width, height, 3)  # 3d -> 4D

result = model.predict(image)
print(result)
pred = np.argmax(result)

if pred == 0:
  print("Hatchback 🚙")
  #  print("\U0001F699")
elif pred==1:
  print("Lorry 🚛")
  # print("\U0001F69A")
elif pred==2:
  # print("")
  print("pickup \U0001F6FB")
elif pred==3:
  print("sedan 🚗")
  # print("\U0001F697")