# -*- coding: utf-8 -*-
"""fashion-mnist-interference.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tpm-LyBspAGwT7RgmSVyKwLBHs7skwKJ
"""

import argparse
import cv2
import numpy as np
from tensorflow.keras.models import load_model


parser = argparse.ArgumentParser(description='fashion mnist interference')

parser.add_argument('--data', type=str, help='data path, Ex: /data/img.jpg', default='test_image.jpg')
parser.add_argument('--model', type=str, help='select the model: mlp | cnn', default='cnn')

args = parser.parse_args()

if args.model == 'cnn':
    model = load_model('cnn-mlp-fashionMnist.h5')
else
    model = load_model('mlp-fashionMnist.h5')

img = cv2.imread(args.data)
img = cv2.resize(img, (28,28))
img = cv2.cvtColor(img, (img, cv2.COLOR_BGR2GRAY))
img = img/255.0
img = img.reshape(28,28,1)

result = np.argmax(model.predict(img))
print(result)